title: "Jack Murrow"
description: "Jack Murrow is a Computer Science and Engineering student at Santa Clara University interested in programming languages, compiler design, and formal methods."

url: "https://jackmurrow.github.io"
baseurl: ""
